# Intro to Numpy
**NumPy** is a library in Python that supports creation and operations on large, multidimensional arrays and matrices. It facilitates scientific and numeric computing with high level mathematical functions to operate on these arrays.

In this micro course we will learn how to use Numpy.

A NumPy object is generally a multi-dimensional array. It is a table of elements with **the same data type** (int, float, char, etc.), indexed by a tuple of positive integers (also called *indices*). In Numpy, dimensions are called *axes*. The number of axes is *rank*. (ref: [scipy.org](https://scipy.org))

Consider a 3D space of x, y and z coordinates. A  point in 3D space is written as

```python
[1.0, 3.0, 5.0] 
```
and is an array of rank 1. If there are several such points as shown below, then the dimensions are of the nature *m by n*. In the example shown below, there are 4 rows and 3 columns (i.e., 3 elements or values for each point/observation), this translates to an n-dimensional array with a shape of 4 by 3.

```python
[[ 1.0, 0.3, 4.5],
 [ 0.5, 1.5, 2.3],
 [ 6.0, 4.6, 3.5],
 [ 4.5, 3.5, 6.3]]
```
We need to import the numpy library to use it. Any python library can be referenced by an alias that is mentioned during the import. For example, NumPy library is most commonly imported in the short form as np:
```python
# Importing the numpy library
import numpy as np
```

There are several ways to initialize an array in numpy :
* a = np.array([0,1,2,3])   ...   creates an array of rank (or dimensionality) 1
* a = np.array([[0,1,2,3],[4,5,6,7]])   ...   creates a 2x4 matrix  
* a = np.ones((3,3))   ...   creates a 3x3 matrix with all 1s
* a = np.zeroes((2,2))   ...   creates a 2x2 matrix with all 0s
* a = np.eye(3)   ...   creates a 3x3 matrix with 1s at the diagonal and 0s otherwise (i.e. an identity matrix)
  
Ref: http://www.numpy.org

We will look at various functions (most widely used functions) within the numpy library and practice applying them.

## 2. Casting a non-array datatype into an array

The np.array() method can be used to convert a variable of any data type into an n-dimensional array. By simply passing the variable as an argument to this function, we can convert the variable which can be an integer, float, list, series or dataframe into an n-dimensional array.

For Example:

```python
a = 5
type(a)
>>> int

a = np.array(a)
type(a)
>>> numpy.ndarray

b = [1.2, 3.4, 5.6]
type(b)
>>> list

b = np.array(b)
type(b)
>>> numpy.ndarray
```

### Exercise:

Given the list of numbers use the np.array() method to cast the list into a numpy array. <br>
you can practice it in the following code cell (or you can download [Anaconda](https://www.anaconda.com/distribution/) and use Jupyter Notebook to practice):<br>

In [ ]:
import numpy as np
a = ['Hello',4,5,17.32,25.21,'c']
# Cast the given list into an array:


### Wait! The above list was heterogenous...

Remember that an array is a collection of homogenous elements. However, in the above exercise the list 'a' was a collection of heterogenous elements/values (values of different datatypes). The np.array() method worked anyway and converted the list into an array. The method acheives this by converting all the list elements into string data types. Another interesting behavior to note is that once the elements are cast as a string data types, they cannot be individually re-cast into integer, float or other data types. All the elements of the array need to be converted.

i.e., In the above example:

```python
print(a[2],type(a[2]))
>>> 5 <class 'numpy.str_'>

# Casting to 'int'
a[2] = int(a[2])
print(a[2],type(a[2]))
>>> 5 <class 'numpy.str_'>
```
There is no change in array element data type, by individual recasting.

## 3. Casting a list of lists into a 2-dimensional array

A list of lists structure can be converted into a 2-D array (or matrix) using the np.array() method.

```python
my_list2 = [[1,2,3],[4,5,6],[7,8,9],[10,11,12]]
list_of_lists = np.array(my_list2)
print(list_of_lists,"\n",type(list_of_lists))
>>> [[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]
  <class 'numpy.ndarray'>
```

## 4. Checking the shape and data type of a Numpy array

The shape of an array can be described as the list of lengths of every dimension pertaining to the array. <br/>
For a 2-dimensional array, shape would be number of rows * number of columns, denoted as $ \text{m} \times \text{n}$ and read as 'm by n' or "m" by "n".
The shape attribute returns the list of all lengths of each dimension of the array, as a 'tuple'.

<b>Note:</b> The length of the tuple returned by 'shape' attribute denotes the dimensionality of the array.

<img src="numpy_1-shape_of_array.png">
<br>

The command shape is used to determine the dimensions of the array.

```python
print(list_of_lists.shape)
>>> (4, 3)
```

The data type of each individual elements in an array can be identified by using the 'dtype' attribute.

```python
my_list2 = [[1,2,3],[4,5,6],[7,8,9],[10,11,12]]
list_of_lists = np.array(my_list2)
print(list_of_lists.dtype)
>>> int32
```

### Exercise:

Find the shape of the array below and assign to the variable: two_d_shape and print it out.
Also find the data type of the elements in the array assign to the variable: two_d_datatype and print it out.

```python
[[1, 0.3, 4.5]
 [2, 4.0, 6.0]]
```

In [ ]:
import numpy as np
two_d_array = np.array([[ 1 ,  0.3,  4.5], [2, 4.0, 6.0]])
# Find the shape and data type for the given array:


## 5. Re-shaping an array

The reshape() function in numpy helps us reshape a given array into an array with a specified new shape. For example,

<img src="numpy_2-reshaping_array.png" width="500">
<br>

```python
n_arr = np.array([[1, 2], [3, 4]])
n_arr
>>> array([[1, 2],
>>>        [3, 4]])
n_arr.shape
>>> (2, 2)

n_arr.reshape(1, 4)
>>> array([[1, 2, 3, 4]])

n_arr.reshape(4, 1)
>>> array([[1],
>>>        [2],
>>>        [3],
>>>        [4]])
```

### Exercise

Change the shape of the given array to 2 rows, 5 columns.

In [ ]:
twor_fivec = np.arange(10)
# Change the shape of the given array to 2 rows, 5 columns:


## 6. Indexing and Selection

The numpy array works like the list data structure and elements can be accessed by using their respective indices. The first element of an array is indexed with a '0' index and subsequent elements are indexed as 1,2,3...and so on, the nth element in the array will have an index of 'n-1'.

<img src="numpy_2-indexing_array.png" width="400">
<br>

```python
n_arr = np.array([1, 7, 4, 3, 3])

n_arr[3:5]
# Selects elements from index '3' to '4' (i.e until, but not including the specified end value)
>>> array([3, 3])

n_arr[:3]
# Absence of start value defaults to index '0' (i.e the first element)
>>> array([1, 7, 4])

n_arr[2:]
# Absence of end value defaults to index 'n-1' (i.e the last element)
>>> array([4, 3, 3])

n_arr[:]
>>> array([1, 7, 4, 3, 3])

n_arr[-1]
# Negative indexing corresponds to counting from the last
>>> 3
```

Elements of a numpy array can also be selected (or conditionally retrieved) by using a condition in place of an index. When an array is subject to a condition (as we will show below), each element of the array will be validated against the condition and a boolean array is generated which reflects the satisfaction of the set condition by every element of the array. When an 'array condition' is used in place of an index, the boolean array so generated gets passed to the outer array, and all elements which lie in the 'True' positions of the boolean array get retrieved. The below examples will clear this concept.

```python
array_one = np.array([16,  1,  8,  1, 17, 10,  8, 15,  6, 14])
array_one > 10
>>> array([ True, False, False, False, True, False, False, True, False, True])

array_one[array_one>10]
>>> array([16, 17, 15, 14])

array_two = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
array_two < 5
>>> array([ True,  True,  True,  True,  True, False, False, False, False, False])

array_two[array_two < 5]
>>> array([0, 1, 2, 3, 4])
```

### Exercise

Retrieve all elements in the given array that are greater than or equal to 25.63

In [ ]:
array_three = np.array([46.56311588, 49.66285409, 28.01145694, 15.4632352, 16.36194605, 
                        23.26915095, 36.77562698, 41.97868793, 35.6520983, 24.85098496])


## 7. Duplicating arrays

**Duplicating** a numpy array is a tricky thing. As per normal programming routines, the value of a variable can be assigned to another variable, thus creating a copy. See example below:
```python
a = 10
b = 10
print(b)
>>> 10
```
However, when the same logic is used in assigning arrays, the values are not assigned but rather the pointers (or addresses) of original array elements are stored in the new array. It is for this reason that, any change in the second array will also reflect in the first array.
```python
arr_1 = np.array([1,2,3,4,5,6,7,8,9])
arr_2 = arr_1
arr_2[3:6] = 4444
print(arr_1,arr_2)
>>> [1, 2, 3, 4444, 4444, 4444, 7, 8, 9] [1, 2, 3, 4444, 4444, 4444, 7, 8, 9]

or

arr_1 = np.array([1,2,3,4,5,6,7,8,9])
arr_2 = arr_1
arr_2[:] = [1,22,333,4444,55555,666666,7777777,88888888,999999999]
print(arr_1,arr_2)
>>> [1, 22, 333, 4444, 55555, 666666, 7777777, 88888888, 999999999] [1, 22, 333, 4444, 55555, 666666, 7777777, 88888888,
>>>  999999999]
```

Hence, when a separate copy of an array is to be made, then the .copy() function needs to be used so as to create a new copy of the array which can be changed, without affecting the original array.

```python
arr_1 = np.array([1,2,3,4,5,6,7,8,9])
arr_2 = arr_1.copy()
arr_2[3:6] = 4444
print(arr_1,arr_2)
>>> [1, 2, 3, 4, 5, 6, 7, 8, 9] [1, 2, 3, 4444, 4444, 4444, 7, 8, 9]
```

### Exercise

Given array 'tran_arr', create two copies of the array - one copy just referencing the values of the original array ('tran_arr') and another copy which duplicates the values of the array using .copy() function. Set 5th element of first copy array to 25, and set 5th element of second copy array to 50. Print all 3 arrays and observe the changes. 

In [ ]:
tran_arr = np.arange(1,21)
copy_1 = []
copy_2 = []


## 8. Array Operations

#### 1.1 Addition of two arrays

To add another array of the same dimension use
```python
C = np.add(A, B)      OR     C = A + B
```

#### 1.2 Subtraction of two arrays

To subtract an array from another array use 
```python
D = np.subtract(A,B)  OR     D = A - B
```

#### 1.3 Multiplication

1. multiply a constant with the elements of the array

```python
K = 10
Y = np.multiply(K,[1, 2, 3, 4, 5])   OR     Y = K * np.array([1, 2, 3, 4, 5])
# Output
>>> array([10, 20, 30, 40, 50])
```
2. multiply an array with another array, performs element-wise multiplication (only if both arrays are of equal shape)

``` python
A = np.array([1,2,3])
B = np.array([4,5,6])
C = np.multiply(A,B)                 OR     C = A * B
# Output
>>> array([ 4, 10, 18])
```

3. dot product of two arrays, calculates sum of product of elements (only if both arrays are of equal shape)

```python
A = np.array([1,2,3])
B = np.array([4,5,6])
C = np.dot(A, B)
# Output
>>> 32
```

4. matrix multiplication (only if number of columns in the 1st one equals the number of rows in the 2nd one)

``` python
A = [[1, 0], [0, 1]]
B = [[4, 1], [2, 2]]
C = np.matmul(A, B)
# Output
>>> array([[4, 1],
       [2, 2]])
```


### Exercise:

Given two arrays:
```python
A = [1, 2, 3, 4]
B = [2, 3, 4, 5]
```

- Initilize the above arrays as variables A & B.
- Perform a dot product of the two vectors and assign it to the variable C.
- Print C.

In [ ]:
import numpy as np


## Learn more about Numpy

In this notebook, we have given you a flavor of the basics of Numpy. Numpy is a powerful library and this notebook is meant to be a starting point. Want to become even more proficient in Numpy and learn more? Check out our courses at https://refactored.ai. Our course on Python covers not just Numpy but many other topics in Python and Machine learning that can help you become a Data Scientist.
