# Introduction to Matrices

## What is a Matrix?

A matrix is a set of numbers, symbols and expressions which are arranged in a rectangular fashion using rows and columns.

Consider a matrix $A$, which consists of 'm' rows and 'n' columns, at the intersection of each row and column, there would be an element of the matrix, which may be a number, symbol or expression. Therefore, in a matrix with 'm' rows and 'n' columns, there would be 'm\*n' elements. The <b>dimensions of the matrix</b> would be m x n (Read as: m cross n), i.e. 'm' rows and 'n' columns.

A matrix is generally denoted by a rectangular array of numbers enclosed within square brackets.

$A = \left[\begin{array}{cc}1 & 2 & 3\\4 & 5 & 6\\7 & 8 & 9\end{array}\right]$

$A$ here is a 3 X 3 matrix and it has 9 elements (also widely referred to as 'entries').

Also, entries in a matrix can be more than just numbers - like symbols and expressions.

$B = \left[\begin{array}{cc}\alpha & \beta \\ \gamma & \delta \\ \lambda & \pi \end{array}\right]$

or

$C = \left[\begin{array}{cc}3x+4y+1 & 2x^2 - 6y^2\\-2x+3y^3 & 5x^2 - 23y + 18\\\end{array}\right]$



## Types of Matrices - 1

Depending mostly upon the nature and positioning of entries, various types of matrices are possible. We will discuss and define a few common and important types of matrices here. Below described matrices are some of the basic types of matrices. We will look at slightly more advanced matrix types in a later section, after learning about matrix operations. For a larger list of various types of matrices refer to (Link: https://en.wikipedia.org/wiki/List_of_matrices)

### Row Matrix

A matrix which consists of one and only one row (there can be any number of columns) is called a 'row matrix'.

For e.g.

$A = \left[\begin{array}{cc}1 & 2 & 3 \end{array}\right]$
<br>or<br>
$B = \left[\begin{array}{cc}\alpha & \beta & \gamma & \delta\\\end{array}\right]$

### Column Matrix

A matrix which consists of entries arranged in one and only one column, is called a 'column matrix'.

For e.g.

$A = \left[\begin{array}{cc}a \\ b \\ c \\d \end{array}\right]$
<br>or<br>
$B = \left[\begin{array}{cc}12 \\ 24 \\36 \end{array}\right]$

### Square Matrix

By definition, matrix is a rectangular array of entries. A square is nothing but a special rectangle where its length equals its breadth. Similarly, a square matrix is one where it has equal number of rows and columns.

For e.g.

$A = \left[\begin{array}{cc}1 & 2 \\ 3 & 4\end{array}\right]$
<br><br>here $A$ is a 2 X 2 square matrix. i.e. 2 rows and 2 columns
<br><br>or<br><br>
$B = \left[\begin{array}{cc}\alpha & \beta & \gamma \\ \delta & \phi & \omega \\ \lambda & \pi & \mu\end{array}\right]$
<br><br>$B$ is a 3 X 3 square matrix.

Note: A square matrix with $n$ x $n$ dimensions will have $n^2$ elements.

Before we discuss further about other types of matrices, we would like to introduce the concept of diagonal elements in a square matrix.

<b>Entries/Elements in a matrix:</b> As we know, by definition the number of columns is equal to the number of columns. Say $i$ is a variable representing the number of row and $j$ be representing the number of column, then the element $x_{ij}$ is nothing but the element present in the intersection of the $i^{th}$ row and $j^{th}$ column. For example:

Let $A$ be a 3 x 3 matrix with the following entries

$A = \left[\begin{array}{cc}1 & 2 & 3\\4 & 5 & 6\\7 & 8 & 9\end{array}\right]$

If $a$ is the symbol of an entry in matrix $A$ then, $a_{31}$ by convention is the element in the 3rd row and 1st column. The row and column numbers may also be separated by a comma or space.

In the above example,<br>
$a_{31} = 7$ <br>
$a_{12} = 2$ <br>
$a_{22} = 5$ and so on.

#### Diagonals of a matrix

Within a square matrix of dimensions n x n, the elements which can be denoted by $a_{ij}$ where $i$ is equal to $j$ are called diagonal elements and they together constitute the diagonal of the square matrix. So all elements of the form $a_{ii}$ where $i$ belongs to [1,2,3...n] consitute the diagonal of the matrix.

In the above example the diagonal of matrix $A$ constitutes the elements {$a_{11}, a_{22}, a_{33}$}, i.e., {1,5,9} are the diagonal elements in the above example. This diagonal is called the primary diagonal or leading diagonal of the matrix. There is also a trailing diagonal or antidiagonal of a square matrix. The below image shows the leading and trailing diagonals in a 3x3 square matrix.
<br>
<img src="https://dsin100days.s3-us-west-2.amazonaws.com/images/images/matrix_dgnl.PNG" style="width:40vw">
<br>

### Diagonal Matrix

The diagonal matrix is a square matrix in which the diagonal elements have some quantitative value and all other elements are zeroes.

For e.g.

$D = \left[\begin{array}{cc}3 & 0 & 0 \\ 0 & 6 & 0 \\ 0 & 0 & 9\end{array}\right]$
<br><br>$D$ is a 3 X 3 diagonal matrix.

There are further two important types of Diagonal Matrices:

#### Unit Matrix or Identity Matrix

This is a diagonal matrix where all the elements of the diagonal are 1.

For e.g.

$I = \left[\begin{array}{cc}1 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 1\end{array}\right]$
<br><br>$I$ is a 3 X 3 unit matrix.

The unit matrix is also called as 'Identity Matrix'. This is because in matrix multiplication (which we will study in the next section) any matrix $S$ of dimensions m x n when multiplied by a unit matrix of dimensions n x n, results in itself. That is, if $S$ is the matrix in question and $I$ is a compatible unit matrix, then -

$S * I = S$

#### Scalar Matrix

This is a diagonal matrix where all the elements of the diagonal are of the same value. It is called a scalar matrix because it can be written as the product of a scalar and an identity matrix.

For e.g.

$S = \left[\begin{array}{cc}7 & 0 & 0 \\ 0 & 7 & 0 \\ 0 & 0 & 7\end{array}\right]$
<br><br>$S$ is a 3 X 3 scalar matrix.

### Zero or Null Matrix

A matrix where all entries are zeroes is called a zero matrix or a null matrix.

For e.g.

$Z_1 = \left[\begin{array}{cc}0 & 0 & 0\\ 0 & 0 & 0\end{array}\right]$
<br><br>
$Z_2 = \left[\begin{array}{cc}0 & 0 \\ 0 & 0\end{array}\right]$
<br><br>
$Z_3 = \left[\begin{array}{cc}0 & 0 & 0 \\ 0 & 0 & 0 \\ 0 & 0 & 0\end{array}\right]$
<br><br>$Z_1, Z_2, Z_3$ are all zero matrices.

## Implementation of Matrices in Python

There are two ways of creating matrices in Python.
1. Declare a list of lists. The number of levels of nesting and the length of each nested list determine the dimensions of the matrix.
2. Initialize a numpy nd-array (n-dimensional array).

For e.g.,

```python
# List of lists implementation
a = [[1,2,3],
     [4,5,6],
     [7,8,9]]

# Nd-array implementation
import numpy as np

a = np.array([[1,2,3],[4,5,6],[7,8,9]])
```

There are also some dedicated functions in numpy to create Null matrices, Identity matrices and matrices where all entries are 1s.

For e.g.,

```python
import numpy as np

# A 3x3 Null matrix
z = np.zeros((3,3))
z

# Output
>>> array([[0., 0., 0.],
>>>        [0., 0., 0.],
>>>        [0., 0., 0.]])

# A 3x3 Identity matrix
i = np.eye(3)
i

# Output
>>> array([[1., 0., 0.],
>>>        [0., 1., 0.],
>>>        [0., 0., 1.]])

# A 3x3 matrix with all entries as 1s
a = np.ones((3,3))
a

# Output
>>> array([[1., 1., 1.],
>>>        [1., 1., 1.],
>>>        [1., 1., 1.]])
```

<b>Question:</b> From the above examples we can observe that 'zeros' and 'ones' function takes a tuple as an argument which specifies the dimensions of the matrix to be created. However, 'eye' function takes only an integer as an argument. Do you know why?
<br>
<b>Answer:</b> A Null matrix is not necessarily a square matrix and can have any dimensions as long as all entries are zeroes. Same goes for the matrix which has 1s as entries, it can have any dimensions. However, an identity matrix is always a square matrix hence one integer value 'n' is enough to create a nxn identity matrix.

#### Exercise

Initialize the following matrices
1. A matrix with entries of integers from 1 through 12, with the dimensions 3x4.
2. Define a scalar_mat() function which takes in 2 elements - 'n' which determines the nxn dimensions of the scalar matrix and 'a' the entry which fills all positions in the primary diagonal. Use this function to create a 4x4 scalar matrix with diagonal elements as 256.
3. A 5x5 identity matrix.

(array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]), array([[256.,   0.,   0.,   0.],
        [  0., 256.,   0.,   0.],
        [  0.,   0., 256.,   0.],
        [  0.,   0.,   0., 256.]]), array([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]]))

### Solution code

```python
import numpy as np

a = np.reshape(np.arange(1,13),(3,4))

def scalar_mat(n,a):
    scalar_matrix = np.zeros((n,n))
    for i in range(0,n):
        scalar_matrix[i][i]=a
    return scalar_matrix

b = scalar_mat(4,256)

c = np.eye(5)

a,b,c
```

## Basic Matrix Operations

Before we learn further about various matrices and their properties, we need to learn basic matrix operations. We will learn about basic arithmetic operations of matrices such as addition, subtraction, multiplication etc. and then we will also learn about special operations specific to matrices.

### Addition and Subtraction

Addition can be performed between two scalars (which is the addition of two numbers), a scalar and a matrix or between two matrices.
* Scalar addition: General addition of two numbers.
```python
a = 5
b = 4
c = a+b
```
* Scalar-Matrix addition: Addition of a scalar value to each value within the given Matrix
<img src="https://dsin100days.s3-us-west-2.amazonaws.com/images/images/mat_scad.PNG" style="width:60vw">
<br>
* Matrix addition: Addition of two matrices. Two matrices can be added, only if they have the same dimensions. This is because matrix addition is nothing but a collection of scalar additions - each entry is added to the entry in the second matrix which is at the same position. i.e., If entries in matrix $A$ are denoted by $a_{ij}$ where $i$ is the row number and $j$ is the column number of the entry, denoting the position of the entry in the matrix, and if in matrix $B$ entries are denoted by $b_{ij}$ then for a given combination of $i$ and $j$, $a_{ij}+b{ij}$ would be the entry in the resulting additive matrix at position $i,j$. Same rules hold true for subtraction. For these operations, matrices can be treated as variables and '+' and '-' operators can be used to perform addition and subtraction.
 
<b>Addition</b>

<img src="../../../images/mat_add.PNG" style="width:60vw">

<br>

<b>Subtraction</b>

<img src="../../../images/mat_sub.PNG" style="width:60vw">
<br>

### Matrix Multiplication and Division(!)

Two matrices can be multiplied with each other if the number of columns of the first matrix is equal to the number of rows of the second matrix. The product of two matrices will be another matrix with dimensions as -
* number of rows equal to the number of rows of first matrix
* number of columns equal to the number of columns of the second matrix

Matrix-to-Matrix multiplication is not element to element operation like addition and subtraction seen above. An element in the product is derived by the sum of products of elements in rows of first matrix and columns of second matrix. It is for this reason that length of each row in first matrix (i.e. number of columns in first matrix) should be equal to the length of each column in second matrix (i.e. number of rows in second matrix).

Scalar-Matrix Multiplication:
<br>
<img src="https://dsin100days.s3-us-west-2.amazonaws.com/images/images/matscal_mul.PNG" style="width:70vw">
<br>

Matrix-to-Matrix Multiplication
<br>
<img src="https://dsin100days.s3-us-west-2.amazonaws.com/images/images/matmul_2.PNG" style="width:70vw">
<br>

This operation can be acheived by using either the 'dot' (dot product) function or the 'matmul' function in numpy module. These functions generally take two arguments, i.e., the two matrices which should be multiplied.

For example:
```python
import numpy as np

a = np.array([[1,2],[3,4]])
b = np.array([[1,2],[2,1]])

print(np.matmul(a,b))

# Output
>>> [[ 5  4]
>>>  [11 10]]

```
<br>
<b>Note:</b> There is no such thing as <b>division operation</b> in matrices. However, a special operation called inverse of a matrix exists which we would learn about in the next notebook.

#### Exercise

Perform addition, subtraction and multiplication operations on the given matrices. Store the result in 3 variables - addition, subtraction and multiplication and print them out.

In [ ]:
import numpy as np

a = np.array([[1,2],[3,4]])
b = np.array([[1,1],[1,1]])

# addition = 
# subtraction = 
# multiplication = 

### Solution code

```python
addition = a+b
subtraction = a-b
multiplication = np.matmul(a,b)

print(addition,"\n",subtraction,"\n",multiplication)
```