# More Matrix Operations and Special Matrices

## Transpose, Determinant and Inverse of a Matrix

### Transpose Operation

A transpose operation on a matrix converts each row of entries into a column and in effect, the rows of original matrix become columns in the transposed matrix and columns of the original matrix become rows in the transposed matrix. i.e., If the dimensions or shape of the matrix is $(i,j)$ then the transpose of this matrix will have a shape of $(j,i)$.

<img src="../../../images/mattran_2.PNG" style="width:40vw">
<br>

numpy.transpose() method can be used to find out the transpose of a matrix.

```python
import numpy as np

a = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(np.transpose(a))

# Output

>>> [[1 4 7]
>>>  [2 5 8]
>>>  [3 6 9]]
```

<b>Note:</b> An interesting point to observe is that the transpose operation does not affect the position of the entries on the primary or leading diagonal of a square matrix.

What about the anti-diagonal (trailing diagonal) entries of the square matrix?
They are reversed in order, i.e., the top most entry becomes the bottom most entry and the bottom most entry becomes the top most.


#### Exercise

Find transpose of the following matrix:

$A = \left[\begin{array}{cc}8 & 15 & 30 \\ 43 & 2 & 9 \\ 11 & 25 & 62\end{array}\right]$

[[ 8 43 11]
 [15  2 25]
 [30  9 62]]


### Solution code

```python
import numpy as np

A = np.array([[8,15,30],[43,2,9],[11,25,62]])

print(np.transpose(A))
```

### Determinant of a Matrix

The determinant of a matrix is a scalar value which holds a significant value in linear operations that can be performed on the matrix. It is a value that can be calculated only for square matrices. For a matrix $A$, it is represented as det(A) or |$A$|.

The determinant is calculated by a series of arithematic operations. The following figure shows calculation of determinant for various matrices.

For a 2x2 matrix:
<br>
<img src="../../../images/det_mat_2.PNG" style="width:40vw">
<br>

For a 3x3 matrix:
<br>
<img src="../../../images/det_mat_3.PNG" style="width:70vw">
<br>

For a 4x4 matrix:
<br>
Follow the same steps as defined above.
1. Exclude row and column that ‘a’ belongs to and calculate determinant for remaining portion of the matrix
2. Add the calculated part to the expression on the right hand side of the equation
3. Repeat steps 1 and 2 for all remaining elements in first row
4. After adding all terms to the right hand side, add alternating ‘–’ and ‘+’ operations to complete the calculation
<br>

For matrices of higher dimensions, determinants are calculated by help of a calculator.

In python, determinant of any matrix (or multi-dimensional array) can be calculated using the 'det' function in the 'linalg' sub-module of the numpy package.

For example:
```python
import numpy as np

a = np.array([[1,2],[3,4]])

print(np.linalg.det(a))

# Output

>>> -2.0000000000000004
```

#### Exercise

Calculate the determinant for the below given matrix.


$A = \left[\begin{array}{cc}8 & 15 & 30 \\ 43 & 2 & 9 \\ 11 & 25 & 62\end{array}\right]$

-2.0000000000000004


### Solution code

```python
import numpy as np

A = np.array([[8,15,30],[43,2,9],[11,25,62]])

print(np.linalg.det(A))
```

### Inverse of a Matrix

For scalar values, we have the concept of 'reciprocal'. If a number is multiplied by its reciprocal the result is '1'. Similarly, there is a matrix called 'Identity matrix' (which we have studied in last notebook) among matrices.

The Inverse of a matrix is similar to 'reciprocal' of a matrix, i.e., when you multiply a matrix and its inverse, the resulting product would be an Identity matrix.

Say, if $A$ is a square matrix of order n x n, and $I$ is a identity matrix of order n x n, then

**<font size="3">$A$ <font face="Times New Roman">*</font> $A^{-1}$ <font face="Times New Roman">=</font> $I$</font>**

Note that Inverse concept among matrices is applicable only in the case of square matrices.

Calculating inverse of a 2x2 matrix is easy, however, inverse calculation for 3x3 or higher dimensions is very complex. See below example for calculation of inverse for a 2x2 matrix.

<br>
<img src="../../../images/mat_inv.PNG" style="width:70vw">
<br>

The Inverse of a matrix can be determined by using the 'inv' function of 'linalg' sub-module of numpy ($numpy.linalg.inv()$). This function can be performed on a numpy array (matrix).


#### Exercise

Calculate the inverse for the below given matrix.

$A = \left[\begin{array}{cc}8 & 15 & 30 \\ 43 & 2 & 9 \\ 11 & 25 & 62\end{array}\right]$

[[ 0.01307782  0.02330701 -0.00971125]
 [ 0.33238379 -0.02149424 -0.15771073]
 [-0.13634598  0.00453192  0.08144503]]


### Solution code

```python
import numpy as np

A = np.array([[8,15,30],[43,2,9],[11,25,62]])

print(np.linalg.inv(A))
```

### Comparing two matrices

The 'equal to' operator, if used to compare the equality of two matrices, first checks whether the dimensions of both matrices are same or not. If they are, then the operator compares each entry of first matrix with corresponding entry in second matrix and returns a boolean matrix of the same dimensions as compared matrices. If we are expecting a single boolean answer for equality of two matrices, the best way to do that is by using the 'allclose' or 'array_equal' functions.

<b>allclose and array_equal functions:</b> numpy.array_equal() method can be used to test whether two arrays are equal to each other in terms of shape and elements. numpy.allclose() function performs the same operation but it has tolerance while matching elements, which enables it to compare floating point elements with varying accuracies/decimals.

For example:
```python
A = np.array([[8,15,30],[43,2,9],[11,25,62]])
B = np.array([[8,15,30],[43,2,9],[11,25,62]])

print(np.allclose(A,B))

# Output
>>> True
```

#### Exercise

Calculate the inverse of the below given matrix. Create an Identity matrix of dimensions equal to the below given square matrix and use the allclose() function to verify whether the product of the below given matrix and its inverse yeilds the identity matrix.

$A = \left[\begin{array}{cc}8 & 15 & 30 \\ 43 & 2 & 9 \\ 11 & 25 & 62\end{array}\right]$

True


### Solution code

```python
import numpy as np

A = np.array([[8,15,30],[43,2,9],[11,25,62]])
A_inv = np.linalg.inv(A)

I = np.eye(3)

print(np.allclose(np.matmul(A,A_inv),I))
```

## Special Matrices

### Symmetric Matrix

A matrix which is equal to its transpose is called a symmetric matrix. If $A$ is a matrix, then $A$ is a symmetric matrix if:

$A^T = A$

An example of symmetric matrix is

$A = \left[\begin{array}{cc}1 & 2 & 3 \\ 2 & 2 & 2 \\ 3 & 2 & 3\end{array}\right]$

Another example:

$B = \left[\begin{array}{cc}3 & 7 & 8 \\ 7 & 1 & 4 \\ 8 & 4 & 8\end{array}\right]$

#### Exercise

Use the transpose function to calculate transposes of above given matrices - $A$ and $B$. Use the allclose() function to verify if they are equal to their respective transpose matrix and verify if $A$ and $B$ are symmetric matrices.

True True


### Solution code

```python
import numpy as np

A = np.array([[1,2,3],[2,2,2],[3,2,3]])
B = np.array([[3,7,8],[7,1,4],[8,4,8]])

A_trans = np.transpose(A)
B_trans = np.transpose(B)

print(np.allclose(A,A_trans), np.allclose(B,B_trans))
```

### Skew-Symmetric Matrix

A matrix is said to be skew-symmetric if its transpose is equal to the negation of the original matrix. i.e., If $A$ is a matrix, then $A$ is a skew-symmetric matrix if:

$A^T = -A$

An example of symmetric matrix is

$A = \left[\begin{array}{cc}0 & 2 & 3 \\ -2 & 0 & 2 \\ -3 & -2 & 0\end{array}\right]$

Another example:

$B = \left[\begin{array}{cc}0 & 7 & 8 \\ -7 & 0 & 4 \\ -8 & -4 & 0\end{array}\right]$

<b>Note:</b> The entries in the primary diagonal of a skew-symmetric matrix are always zeros and the entries on the upper side of the primary diagonal are all positive while the entries on the lower side of the primary diagonal are all negative.

#### Exercise

Use the transpose function to calculate transposes of above given matrices - $A$ and $B$. Use the allclose() function to verify if the transposes of the matrices are equal to a negated version of their original matrix and verify if $A$ and $B$ are skew-symmetric matrices.

True True


### Solution code

```python
import numpy as np

A = np.array([[0,2,3],[-2,0,2],[-3,-2,0]])
B = np.array([[0,7,8],[-7,0,4],[-8,-4,0]])

A_trans = np.transpose(A)
B_trans = np.transpose(B)

print(np.allclose(-A,A_trans), np.allclose(-B,B_trans))
```

### Singular Matrix

A singular matrix is one for which no inverse exists. This is possible when the determinant of the matrix is zero. Let us say $A$ is a matrix, $A$ is said to be singular if

det($A$)=0

thereby, <br>

$A^{-1}$ = undeterminable

An example of singular matrix is:

$A = \left[\begin{array}{cc}2 & 2 \\ 2 & 2 \end{array}\right]$

another example:

$B = \left[\begin{array}{cc}5 & 4 \\ 10 & 8 \end{array}\right]$

A 3x3 singular matrix:

$C = \left[\begin{array}{cc}0 & 2 & 3 \\ -2 & 0 & 2 \\ -4 & 0 & 4\end{array}\right]$


#### Exercise

Try to calculate determinants of above given matrices $A, B, and C$ and verify if they are truly singular matrices or not.

Also, try calculating the inverse of any of these matrices and observe the output.

0.0 0.0 0.0


### Solution code

```python
import numpy as np

A = np.array([[2,2],[2,2]])
B = np.array([[5,4],[10,8]])
C = np.array([[0,2,3],[-2,0,2],[-4,0,4]])

print(np.linalg.det(A),np.linalg.det(B),np.linalg.det(C))
print(np.linalg.inv(A))
```