## Lab - Matrices

Create the following matrices...

$A = \left[\begin{array}{cc}10 & 95 & 8 \\ 95 & 20 & 9 \\ 8 & 9 & 30\end{array}\right]$

$B = \left[\begin{array}{cc}5 & 8 & 3 & 6\\ 95 & 20 & 9 & 3\\ 8 & 9 & 30 & 3\\ 8 & 9 & 30 & 3\end{array}\right]$

$C = \left[\begin{array}{cc}0 & 6 & 250 \\ -6 & 0 & 86.3 \\ -250 & -86.3 & 0\end{array}\right]$

...calculate...

1. Transpose of A,B and C
2. Inverse of A, B and C

...answer the following...

* What type of matrices are A, B and C

...and perform the below given operations

1. Add A and B. Is the additive result a special type of matrix? If yes, then what type of matrix is it?
2. Multiply A and C. Is the product a special type of matrix? If yes, then what type of matrix is it?

In [ ]:
import numpy as np 
A = np.array([[10, 95, 8], [95, 20, 9], [8, 9, 30]])
B  = np.array([[5, 8, 3, 6], [ 95, 20, 9, 3], [ 8, 9, 30, 3], [8, 9, 30, 3]])
C = np.array([[0, 6, 250 ], [-6, 0, 86.3], [-250, -86.3, 0]])

type_A = ## Get type of matrix A 
type_B = ## Get type of matrix B
type_C = ## Get type of matrix C

print(" A, B and C are matrices of type {}, {}, {}".format(type_A, type_B, type_C))

 A, B and C are matrices of type <class 'numpy.ndarray'>, <class 'numpy.ndarray'>, <class 'numpy.ndarray'>

In [ ]:
# transpose of the matrices
A_T = ## Get transpose of matrix A
B_T = ## Get transpose of matrix B
C_T = ## Get transpose of matrix C
print("A transpose is  \n {}".format(A_T)) 
print("B transpose is \n {}".format(B_T)) 
print("C transpose is \n {}".format(C_T)) 


A transpose is  
 [[10 95  8] <br>
 [95 20  9] <br>
 [ 8  9 30]] <br>
B transpose is <br>
 [[ 5 95  8  8] <br>
 [ 8 20  9  9] <br>
 [ 3  9 30 30] <br>
 [ 6  3  3  3]] <br>
C transpose is <br>
 [[   0.    -6.  -250. ] <br>
 [   6.     0.   -86.3] <br>
 [ 250.    86.3    0. ]] <br>

Let us check each matrix for three things - Is it Symmetric, Skew Symmetric, Singular 
Remember - 
* Symmetric  is $A^T = A$ 
* Skew Symmetric is  $A^T = -A$
* Singular  is $ \text{det}(A) = 0$


At this point, we already have the transposed values so its easy to check if all the matrices are Symmetric, Skew Symmetric or Singular. Since we have three matrices and we need to do the same thing on all three matrices, we are going to write a function to solve this problem. 


In [ ]:
# Starting with matrix A 
def check_matrices(mat): 
    mat_T = np.transpose(mat)
    
   
    sym_check = ## Check if mat and mat_T are array equal
    sksym_check = ## Check if minus mat and mat_T are array equal
    singular_check = ## Using the numpy linear algebra package, calcuate the determinant
    
    ## Write a dict called results wehre you store the answers based on the keys 
    ## symmetric, ske_skymmetric and singular  
    return results 


results_A  = check_matrices(A)
results_B = check_matrices(B)
results_C = check_matrices(C)

print("Results from check matrices for A: \n {}".format(results_A))
print("Results from check matrices for B: \n {}".format(results_B))
print("Results from check matrices for C: \n {}".format(results_C))

# Are A, B and C singular? 
singular_A = "Non singular"
singular_B = "Singular"
singular_C = "Singular"

print("A is {}, B is {}, C is {}".format(singular_A, singular_B, singular_C))

Results from check matrices for A:  <br>
 {'symmetric': True, 'skew_symmetric': False, 'singular': -253159.99999999977}<br>
Results from check matrices for B: <br>
 {'symmetric': False, 'skew_symmetric': False, 'singular': 0.0} <br>
Results from check matrices for C:  <br>
 {'symmetric': False, 'skew_symmetric': True, 'singular': 6.827871601444718e-12} <br>
A is Non singular, B is Singular, C is Singular <br>

In [ ]:
# Add matrices A and B 
print("result of A + B is {}".format('####'))


In [ ]:
matmul_AC  = # matrix multiply matrices A and C using numpy 
print("matrix multiplication of A and C is : \n {}".format(matmul_AC))


[[-2570.   -630.4 10698.5] <br>
 [-2370.   -206.7 25476. ] <br>
 [-7554.  -2541.   2776.7]] <br>
 