# Lab: Numpy
Numpy is one of the most important python libraries. The vectorized operations that numpy performs makes it efficent for numerical calculation.


In [1]:
from sklearn.datasets import load_iris
import random
import numpy as np

iris_dataset = load_iris()
target = list(iris_dataset.target) 
dataset = list(iris_dataset.data)
target_names = list(iris_dataset.target_names)


random.seed(1)
indx_array = np.arange(0,len(target))
np.random.shuffle(indx_array)

np_target = np.array(target)
randomized_target = np_target[indx_array]


Many of the operations we performed in the previous labs can be easily performed using numpy. Take for example mean.

In [2]:
# Convert dataset to an array
dataset_np = "####"

# Slice the dataset array to find the first column 
first_col = "####"

# Calculate the mean of the first column 
mean_first_col = "####"

# Calculate the mean of all the columns by setting axis=0 in np.mean
mean_all_cols = "####"

# Calcuate the mean of all the rows by setting axis=1 in np.mean
mean_all_rows = "####"

# Get the shape of mean_all_rows 
mean_rows_shape ="####"

# There are many situations where you may have to add an extra dimension 
# to a numpy array, you can do this by using np.newaxis. You can add 
# new axis like this  array = array[:, np.newaxis]
mean_all_rows = "####"
new_rows_shape = "####"



Shape of arry representing mean value dataset: (150,), (150, 1)


In [3]:
# Find the max and min in each row and column.
row_max = "####"
row_min = "####"

col_max = np.max(dataset_np, axis=0)
col_min = np.min(dataset_np, axis=0)


There are many times where you may need to randomly choose rows from a dataset. You can do this by using ```np.random.choice``` check out the numpy documentation [here](https://docs.scipy.org/doc//numpy-1.10.4/reference/generated/numpy.random.choice.html). Use this function to do the exercise below

In [4]:
# Randomly sample 5 rows from dataset_np 
np.random.seed(1)

# Start by choosing 5 indices. Use np.random.choice for this. 
# the syntax will be similar to np.random.choice(number of indicies, sample size).
# You can get the number of indices from the shape of dataset_loc
indicies = "####"

# Slice dataset_np with the indicies to get rows 
rows = "####"

print("5 randomly sampled rows : \n {}".format(rows))

5 randomly sampled rows : 
 [[4.9 3.6 1.4 0.1]
 [6.7 3.1 5.6 2.4]
 [6.3 2.5 4.9 1.5]
 [6.4 3.1 5.5 1.8]
 [6.3 2.8 5.1 1.5]]


5 randomly sampled rows : <br>
 [[4.9 3.6 1.4 0.1] <br>
 [6.7 3.1 5.6 2.4] <br>
 [6.3 2.5 4.9 1.5] <br>
 [6.4 3.1 5.5 1.8] <br>
 [6.3 2.8 5.1 1.5]] <br>

Next we are going to build a min-max scaler. The min-max scaler is a function that you can find in sklearn but we will build it using numpy. The min-max scaler reduces the values in dataset to between 0 and 1. This is useful since many machine learning algorithms work between if values lie between 0 and 1. 

Min-max scaling is done in the following way: <br>

$\text{Scaled data}= \dfrac{\text{Column Data} - \text{Min(Column data)} }{\text{Max(Column data)}- \text{Min(Column data)} }$ 

Since our dataset has multiple columms, we would have to find the min and max for each column. In the above exercise we discussed how to do that so apply that below to build the min max scaler. 

In [6]:
# Find the max of all the columns of dataset_np
max_dataset = "####"

# Find the min of the all the columns of dataset_np
min_dataset = "####"

# Apply the formula showed above. We use dataset_np instead of column data
dataset_scaled = "####"
print("First 5 rows of scaled datset : \n{}".format(dataset_scaled[0:5,:]))

First 5 rows of scaled datset : 
[[0.22222222 0.625      0.06779661 0.04166667]
 [0.16666667 0.41666667 0.06779661 0.04166667]
 [0.11111111 0.5        0.05084746 0.04166667]
 [0.08333333 0.45833333 0.08474576 0.04166667]
 [0.19444444 0.66666667 0.06779661 0.04166667]]


First 5 rows of scaled datset :  <br>
[[0.22222222 0.625      0.06779661 0.04166667] <br>
 [0.16666667 0.41666667 0.06779661 0.04166667]<br>
 [0.11111111 0.5        0.05084746 0.04166667] <br>
 [0.08333333 0.45833333 0.08474576 0.04166667]<br>
 [0.19444444 0.66666667 0.06779661 0.04166667]]<br>
