# Numpy II

## 1. NumPy Array Operations
 
<br>
In this lesson we shall study various operations on numpy arrays. 

#### 1.1 Addition of two arrays

To add another array of the same dimension use
```python
C = np.add(A, B)      OR     C = A + B
```

#### 1.2 Subtraction of two arrays

To subtract an array from another array use 
```python
D = np.subtract(A,B)  OR     D = A - B
```

#### 1.3 Multiplication

Using \_\_np.multiply\_\_ (or the \_\_\* symbol\_\_) you can

<b>1. multiply a constant with the elements of the array</b>
```python
K = 10
Y = np.multiply(K,[1, 2, 3, 4, 5])   OR     Y = K * np.array([1, 2, 3, 4, 5])

# Output
>>> array([10, 20, 30, 40, 50])
```
<b>2. multiply an array with another array, performs element-wise multiplication (only if both arrays are of equal shape)</b>
``` python
A = np.array([1,2,3])
B = np.array([4,5,6])
C = np.multiply(A,B)                 OR     C = A * B

# Output
>>> array([ 4, 10, 18])
```

Using \_\_np.dot\_\_ you can perform

<b>3. dot product of two arrays, calculates sum of product of elements (only if both arrays are of equal shape)</b>
```python
A = np.array([1,2,3])
B = np.array([4,5,6])
C = np.dot(A, B)

# Output
>>> 32
```

Using \_\_np.matmul\_\_ you can perform

<b>4. matrix multiplication (only if number of columns in the 1st one equals the number of rows in the 2nd one)</b>
``` python
A = [[1, 0], [0, 1]]
B = [[4, 1], [2, 2]]
C = np.matmul(A, B)

# Output
>>> array([[4, 1],
       [2, 2]])
```


### Exercise:

Given two arrays:
```python
A = [1, 2, 3, 4]
B = [2, 3, 4, 5]
```

- Initilize the above arrays as variables A & B.
- Perform a dot product of the two vectors and assign it to the variable C.
- Print C.

In [1]:
import numpy as np

### Solution code

```python
A = np.array([1, 2, 3, 4])
B = np.array([2, 3, 4, 5])

C=np.dot(A,B)
C
```

## 2. Max, Min, ArgMax, ArgMin

Four simple functions that help a great deal when performing numerical computations on a large array of data is max(), min(), argmax() and argmin().

* max() - can be used to find out what is the maximum value in a given array
* min() - can be used to find out what is the minimum value in a given array
* argmax() - can be used to find out what is the index position of the maximum value in the given array
* argmin () - can be used to find out what is the index position of the minimum value in the given array

For this we are going to use the shape_shifter variable from the last notebook. You can generate your own set of values using 



```python

your_own_array = np.random.rand(12)

# from numpy_1 notebook 
shape_shifter

# Output
>>> array([ 0.906423  ,  0.55807204,  0.28928162,  0.47020116,  0.27403332,
>>>         0.94178672,  0.81342077,  0.5859645 ,  0.63569185,  0.84614272,
>>>         0.36454835,  0.63664789])

shape_shifter.max()
# Output
>>> 0.94178671566784411

shape_shifter.min()
# Output
>>> 0.27403331882439208

shape_shifter.argmax()
# Output
>>> 5

shape_shifter.argmin()
# Output
>>> 4
```

### Exercise

An array is created below. Use the max, min, argmax and argmin functions on the given array and print the results out

In [6]:
# Edit the code below

X = np.array([70, 81, 80, 55, 48, 17, 60, 80, 20, 46])
# max_X = 
# min_X = 
# argmax_X = 
# argmin_X = 

Shape of the array is:  (4, 3, 2, 2) 
 10


### Solution code

```python
max_X = X.max()
min_X = X.min()
argmax_X = X.argmax()
argmin_X = X.argmin()
print("Max value is %d,\nMin value is %d,\nMax value index is %d,\nMin value index is %d"
      %(max_X,min_X,argmax_X,argmin_X))
```

## 3. More array operations and attributes

Common operations such as square root and exponential functions can be computed with the extensions that are common to most other languages such as :

```python
# Usage of square root and exponential
numpy.sqrt(B), numpy.exp(A), 
```

Below is a list of functions (and some attributes which can be extracted) that can be performed on a given array. Observe that the print statement details the functionalities of each of the specific functions.

```python
# Importing numpy library
import numpy as np

# data
a = np.array([366,4,6,74,243,45,234,636,223,7,2,574])

# Printing results
print('''Array of cummulative sums of elements of the original array: {},
         Array of cummulative products of elements of the original array: {},
         Average of all elements of the array: {:.2f},
         Sum of all elements of the array: {},
         Product of all elements of the array: {},
         Standard deviation of all elements of the array: {:.2f}'''.format(
         a.cumsum(),
         a.cumprod(),
         a.mean(),
         a.sum(),
         a.prod(),
         a.std())

# Output
>>> Array of cummulative sums of elements of the original array: [ 366  370  376  450  693  738  972 1608 1831 1838 1840 2414],
>>> Array of cummulative products of elements of the original array: [ 366  1464  8784  650016  157953888  -1482009632  1102097088  854078720  1480993536  1777020160  -740926976  -90321920],
>>> Average of all elements of the array: 201.17,
>>> Sum of all elements of the array: 2414,
>>> Product of all element of the array: -90321920,
>>> Standard deviation of all elements of the array: 214.76

# Sorting array in-place, this changes the original array vs the built-in sorted method which does not affect original array
a.sort()

# Sorted array
a

# Output
>>> array([  2,   4,   6,   7,  45,  74, 223, 234, 243, 366, 574, 636])
```

Some functions that can be performed on 2-dimensional arrays are:
* diagonal() - This function returns the diagonal elements of an n-dimensional array (required - where number of elements on each dimension is equal). When diagonal function is applied on n-dimensional array which have unequal dimension lengths, the function considers the largest possible equal-dimension data structure among the given data array and prints the diagonal elements of that data structure.
* flatten() - This function collapses the multi-dimensional array into a 1-dimensional array and returns it.
* transpose() - This function returns the transpose of the given n-dimensional array, i.e., swaps the elements on dimensions. In a 2-dimensional array, rows become columns and columns become rows.

Examples:
```python
# Importing numpy library
import numpy as np

# data
b = np.array([[366,4,6],[74,243,45],[234,636,223]])

# Printing results
print('''b is a {:d}-dimensional array,
         Diagonal of b is: {},
         1-dimensional equivalent of b is: {},
         Transpose of b is: {}'''.format(
         len(b.shape),
         b.diagonal(),
         b.flatten(),
         b.transpose()))
         
# Output
>>> b is a 2-dimensional array,
>>> Diagonal of b is: [366 243 223],
>>> 1-dimensional equivalent of b is: [366   4   6  74 243  45 234 636 223],
>>> Transpose of b is: [[366  74 234]
>>> [  4 243 636]
>>> [  6  45 223]]
```

#### Exercise

Given a = [52,64,35,6,67,24,12,36,2], Find:
* shape of the array
* index of maximum value element
* average of all elements of the array
* Cummulative sum of the first 6 elements

In [ ]:
# Importing numpy
import numpy as np

# data
a = np.array([52,64,35,6,67,24,12,36,2])

### Solution code

```python
print('''Shape of array 'a':{},
         Index of element with maximum value: {},
         Average of all elements of the array: {},
         Cummulative sum of first 6 elements of the array: {}'''.format(a.shape,a.argmax(),a.mean(),a.cumsum()[5]))
```

## 4. Some special numpy functions

### 4.1 arange() function

There is a basic function in python to generate a list of values. **range**(lower, upper, increment) - where the function starts from the lower value and iterates the value using increment, up to the upper value(exclusive). <br>
Numpy's **arange**(lower, upper, increment) function has the same functionality, except that the output of this function would be an array with the iterated values.

For example:
```python
np.arange(1,5)
>>> array([1, 2, 3, 4])

np.arange(1,11,2)
>>> array([1, 3, 5, 7, 9])

np.arange(11,1,-2)
>>> array([11,  9,  7,  5,  3])
```

### Exercise

Create 2 arrays with values 1,2,3,4 and 5.
* first array using **range()** function
* second array using **arange()** function

In [ ]:
array_one = []
array_two = []

### Solution code

```python
array_one = []
for i in range(1,6):
    array_one.append(i)
array_one = np.array(array_one)
array_two = np.arange(1,6)

print(array_one, array_two)
```

### 4.2 linspace() function

The linear space function creates an array of values which are equally spaced within specified limits. The function accepts a lower limit, an upper limit and the length of the array(say 'n') and it generates _'n'_ equally spaced elements from lower limit to upper limit (inclusive).

```python
np.linspace(1,5,5)
>>> array([ 1.,  2.,  3.,  4.,  5.])

np.linspace(0,1,10)
>>> array([ 0.        ,  0.11111111,  0.22222222,  0.33333333,  0.44444444,
         0.55555556,  0.66666667,  0.77777778,  0.88888889,  1.        ])

np.linspace(-6,6,5)
>>> array([-6., -3.,  0.,  3.,  6.])
```

### Exercise

Initialize and print:
* a linearly spaced array with 5 values between 5 and 50

In [ ]:
# Modify code below

lin_arr = []

### Solution code

```python
lin_arr = np.linspace(5,50,5)
lin_arr
```

### 4.3 Zeros, Ones and Eye

The **np.zeros()** and **np.ones()** functions are used to create n-dimensional arrays with all elements as zeros or ones respectively. Such arrays are extremely useful in many numeric and mathematical operations. The functions take the shape of the array that is to be created, as the argument.

```python
np.zeros(1,5)
>>> array([[ 0.,  0.,  0.,  0.,  0.]])

np.ones((2,4))
>>> array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])
```

The **np.eye()** function creates a square matrix, nxn, with all diagonal elements as ones and all non-diagonal elements are zeros. In mathematics, such kind of a matrix is called the "Identity Matrix", as the multiplicative product of any matrix A and the appropriate identity matrix, is always A itself.

``` python
np.eye(2)
>>> array([[1., 0.],
       [0., 1.]])
```
<img src="../../../images/numpy_1-zeroes_ones_eye.png">
<br>

### Exercise

Initiate three arrays:
* A zeros array of shape (3,3)
* A ones array of shape (4,4)
* A 3x3 Identity Matrix

In [ ]:
# Modify code below

zeros_arr = []
ones_arr = []
eye_mat = []

### Solution code

```python
zeros_arr = np.zeros((3,3))
ones_arr = np.ones((4,4))
eye_mat = np.eye(3)
```