# Linear Algebra - Basics

# Introduction to Linear Algebra

Linear algebra is the branch of mathematics which deals with straight lines, vectors, matrices, multi-dimensional arrays (constructed using linear structures like straight lines or linear planes etc.) and the linear relationships or mappings among these constructs. A set of points or co-ordinates which satisfy a linear equation consitute a 'hyperplane' in an n-dimensional space. The intersection of two hyperplanes is a straight line and the intersections of multiple hyperplanes is a single point, generally regarded as the 'origin'.

## Scalars, Vectors, Matrices and Tensors

A single number (generally rational number) is called a 'scalar'. A single point in space can be represented by a set of co-ordinates or scalars, and this is called a 'vector'. In programming parlance, a vector is an array of numbers (scalars). A Matrix is a 2-dimensional array of numbers, or a collection of vectors. A 'tensor' is a multi-dimensional array.

<img src="https://s3.amazonaws.com/refactored/images/ML/images/svmt_new.png", style="width:70%;">

A 'scalar' can be a numeric variable, an numpy array with numbers is a 'vector'. Similarly, a two-dimensional array can be a matrix and a multi-dimensional array is a 'tensor'. A tensor is generally defined as a geometric object which could represent the linear relationship between scalars, vectors or other tensors (Source: Wikipedia).

## Matrix Operations - Addition, Subtraction, Multiplication, Transpose and Inverse

### Addition and Subtraction

Two matrices can be added, only if they have the same dimensions. While implementing matrices using numpy arrays, the shapes of both arrays need to match in order to perform addition. Same rules hold true for subtraction. For these operations, matrices can be treated as variables and '+' and '-' operators can be used to perform addition and subtraction.
 
Addition

$\left[\begin{array}{cc}x_{11} & x_{12}\\x_{21} & x_{22}\\\end{array}\right] + \left[\begin{array}{cc}y_{11} & y_{12}\\y_{21} & y_{22}\\\end{array}\right]$ = $\left[\begin{array}{cc}(x_{11}+y_{11}) & (x_{12}+y_{12})\\(x_{21}+y_{21}) & (x_{22}+y_{22})\\\end{array}\right]$

<br>
Subtraction

$\left[\begin{array}{cc}x_{11} & x_{12}\\x_{21} & x_{22}\\\end{array}\right] - \left[\begin{array}{cc}y_{11} & y_{12}\\y_{21} & y_{22}\\\end{array}\right]$ = $\left[\begin{array}{cc}(x_{11}-y_{11}) & (x_{12}-y_{12})\\(x_{21}-y_{21}) & (x_{22}-y_{22})\\\end{array}\right]$
<br>

### Mutliplication

Two matrices can be multiplied with each other if the number of columns of the first matrix is equal to the number of rows of the second matrix. The product of two matrices will be another matrix with dimensions as number of rows equal to the number of rows of first matrix and number of columns equal to the number of columns of the second matrix. Matrix multiplication is not element to element operation like addition and subtraction seen above. An element in the product is derived by the sum of products of elements in rows of first matrix and columns of second matrix. It is for this reason that length of each row in first matrix (i.e. number of columns in first matrix) should be equal to the length of each column in second matrix (i.e. number of rows in second matrix). This operation can be acheived by using either the 'dot' (dot product) function or the 'matmul' function in numpy module. These functions generally take two arguments, the two matrices which should be multiplied.

<img src="https://s3.amazonaws.com/refactored/images/ML/images/matmul.png", style="width:70%;">

$\left[\begin{array}{cc}x_{11} & x_{12}\\x_{21} & x_{22}\\x_{31} & x_{32}\\\end{array}\right] * \left[\begin{array}{cc}y_{11} & y_{12} & y_{13} & y_{14}\\y_{21} & y_{22} & y_{23} & y_{24}\\\end{array}\right]$ = $\left[\begin{array}{cc}(x_{11}*y_{11})+(x_{12}*y_{21}) & (x_{11}*y_{12})+(x_{12}*y_{22}) & (x_{11}*y_{13})+(x_{12}*y_{23}) & (x_{11}*y_{14})+(x_{12}*y_{24})\\(x_{21}*y_{11})+(x_{22}*y_{21}) & (x_{21}*y_{12})+(x_{22}*y_{22}) & (x_{21}*y_{13})+(x_{22}*y_{23}) & (x_{21}*y_{14})+(x_{22}*y_{24})\\(x_{31}*y_{11})+(x_{32}*y_{21}) & (x_{31}*y_{12})+(x_{32}*y_{22}) & (x_{31}*y_{13})+(x_{32}*y_{23}) & (x_{31}*y_{14})+(x_{32}*y_{24})\\\end{array}\right]$
<br>

### Exercise

Perform addition, subtraction and multiplication operations on the given matrices. Store the result in 3 variables - addition, subtraction and multiplication and print them out.

In [13]:
import numpy as np

a = np.array([[1,2],[3,4]])
b = np.array([[1,1],[1,1]])

# addition = 
# subtraction = 
# multiplication = 

### Hint

Use matmul function for matrix multiplication

In [14]:
addition = a+b
subtraction = a-b
multiplication = np.matmul(a,b)

print(addition,"\n",subtraction,"\n",multiplication)

[[2 3]
 [4 5]] 
 [[0 1]
 [2 3]] 
 [[3 3]
 [7 7]]


In [15]:
ref_tmp_var = False

try:
    test1 = [[2,3],[4,5]]
    test2 = [[0,1],[2,3]]
    test3 = [[3,3],[7,7]]

    if np.array_equal(test1,addition) and np.array_equal(test2,subtraction) and np.array_equal(test3,multiplication):
        ref_assert_var = True
        ref_tmp_var = True
    else:
        ref_assert_var = False
        print('Please follow the instructions given and use the same variables provided in the instructions. ')
except Exception:
    print('Please follow the instructions given and use the same variables provided in the instructions. ')

assert ref_tmp_var

True



<br/><br/><br/>
### Transpose

A transpose of a matrix is another matrix which results from transforming all the rows of elements of the original matrix into columns. If the order or shape of the matrix is $(i,j)$ then the transpose of this matrix will have a shape of $(j,i)$.

<img src="https://s3.amazonaws.com/refactored/images/ML/images/mattran.png", style="width:70%;">

$\left(\left[\begin{array}{cc}x_{11} & x_{12}\\x_{21} & x_{22}\\\end{array}\right]\right)^T$ = $\left[\begin{array}{cc}x_{11} & x_{21}\\x_{12} & x_{22}\\\end{array}\right]$

numpy.transpose() method can be used to find out the transpose of a matrix.

### Inverse of a Matrix

In mathematics, we have the concept of 'reciprocal'. If a number is multiplied by its reciprocal the result is '1'. Similarly, there is a matrix called 'Identity matrix' which is analogous to the '1' among numbers. An Identity matrix has all elements as zero except elements on its principal diagonal which are all ones.

Identity Matrix $(2x2)$ = $\left[\begin{array}{cc}1 & 0\\0 & 1\\\end{array}\right]$

Identity Matrix $(3x3)$ = $\left[\begin{array}{cc}1 & 0 & 0\\0 & 1 & 0\\0 & 0 & 1\\\end{array}\right]$

The Inverse of a matrix is the matrix which when multiplied with the original matrix, results in a Identity matrix.

**<font size="3">A <font face="Times New Roman">*</font> A<sup>-1</sup> <font face="Times New Roman">=</font> I</font>**

Note that Inverse concept among matrices is applicable only in the case of square matrices.

The Inverse of a matrix can be determined by using the 'inv' function of 'linalg' sub-module of numpy ($numpy.linalg.inv()$). This function can be performed on a numpy array (matrix).

<b>Generating Identity matrices in numpy:</b> numpy.eye() method can be used to generate an identity matrix. The argument 'N', is an integer which determines the order of the square matrix. E.g., numpy.eye(2) generates a 2x2 identity matrix and numpy.eye(3) generates a 3x3 matrix and so on.

<b>allclose and array_equal functions:</b> numpy.array_equal() method can be used to test whether two arrays are equal to each other in terms of shape and elements. numpy.allclose() function performs the same operation but it has tolerance while matching elements, which enables it to compare floating point elements with varying accuracies/decimals.

The above two methods can be used to verify if a matrix is indeed an inverse of another matrix.

numpy.allclose(numpy.matmul(a,b),numpy.eye(order of a or b))

Here, order of matrix 'a' should be equal to matrix 'b' and they both should be square matrices. Hence, shape of a and b will be (i,i) and order of a or b would be just 'i' and not (i,i). The above functions returns 'true' if b is an inverse of a, and 'false' if it is not.

### Exercise

Find out the transpose and inverse of the given matrix. Store the results in variables called 'atranspose' and 'ainverse' respectively and print them out. Also verify 

In [16]:
a = np.array([[1,2],[3,4]])

# atranspose = 
# ainverse = 

### Hint

Use numpy.linalg.inv() method

In [17]:
atranspose = np.transpose(a)
ainverse = np.linalg.inv(a)
print(atranspose,"\n",ainverse)
np.allclose(np.matmul(a,ainverse),np.eye(2))

[[1 3]
 [2 4]] 
 [[-2.   1. ]
 [ 1.5 -0.5]]


True

In [18]:
ref_tmp_var = False

try:
    test1 = np.array([[-2.,1.],[1.5,-0.5]])
    test2 = np.array([[1,3],[2,4]])

    if np.allclose(test1,ainverse) and np.array_equal(atranspose,test2):
        ref_assert_var = True
        ref_tmp_var = True
    else:
        ref_assert_var = False
        print('Please follow the instructions given and use the same variables provided in the instructions. ')
except Exception:
    print('Please follow the instructions given and use the same variables provided in the instructions. ')

assert ref_tmp_var

True



<br/><br/><br/>
## Vector Operations - Dot Product and Cross Product

Assume two vectors, 'a' and 'b' having elements **(x<sub>1</sub>,x<sub>2</sub>,x<sub>3</sub>)** and **(y<sub>1</sub>,y<sub>2</sub>,y<sub>3</sub>)** respectively.

Dot product of a and b is:<br>
**a.b = x<sub>1</sub>y<sub>1</sub> + x<sub>2</sub>y<sub>2</sub> + x<sub>3</sub>y<sub>3</sub>**<br><br>
According to the law of cosines, dot product can also be written as:<br>
**a.b = ||a|| ||b|| cos($\theta$)**<br>

Cross product of a and b is:<br>
**axb = $\left|\begin{array}{cc}x_{2} & x_{3}\\y_{2} & y_{3}\\\end{array}\right|i - \left|\begin{array}{cc}x_{1} & x_{3}\\y_{1} & y_{3}\\\end{array}\right|j + \left|\begin{array}{cc}x_{1} & x_{2}\\y_{1} & y_{2}\\\end{array}\right|k $**<br><br>
It can also be written geometrically as:<br>
**||axb|| = ||a|| ||b|| sin($\theta$) **<br>

Note that dot product of two vectors returns a scalar and cross product of two vectors returns another vector. Dot product for one-dimensional arrays or vectors can be performed using numpy.dot() method where it will return inner product of the two vectors (for matrices the same function returns matrix multiplication result). Cross product of two one-dimensional vectors can be found by using the method numpy.cross().

### Exercise

Find the dot product and cross product for the given vectors. Store the result in variables prod_dot and prod_cross, and print them out.

In [20]:
vector_one = np.array([1,2,3])
vector_two = np.array([1,1,1])

# prod_dot =
# prod_cross =

### Hint

In [21]:
prod_dot = np.dot(vector_one, vector_two)
prod_cross = np.cross(vector_one, vector_two)

print(prod_dot,"\n",prod_cross)

6 
 [-1  2 -1]


In [22]:
ref_tmp_var = False

try:
    var = 6
    test = np.array([-1,2,-1])

    if prod_dot == var and np.allclose(prod_cross,test):
        ref_assert_var = True
        ref_tmp_var = True
    else:
        ref_assert_var = False
        print('Please follow the instructions given and use the same variables provided in the instructions. ')
except Exception:
    print('Please follow the instructions given and use the same variables provided in the instructions. ')

assert ref_tmp_var

True



<br/><br/><br/>
## Norm of a vector and types of vectors

The norm of a vector is a numeric value which represents the lenght or size of the vector. It is defined as

**L<sup>p</sup> = ||x||<sub>p</sub> = ($\sum_{i}$|x<sub>i</sub>|<sup>p</sup>)<sup>1/p</sup>**

1. L<sup>1</sup> Norm: It is also known as least absolute error <br>
If x = [1,-2,3], then<br>
**L<sup>1</sup> of x = |x<sub>1</sub>| + |x<sub>2</sub>| + |x<sub>3</sub>| = |1| + |-2| + |3| = 6**<br><br>

2. L<sup>2</sup> Norm: It is also known as least squares <br>
For x, as given above<br>
**L<sup>2</sup> of x = $\sqrt{|x_{1}|^{2} + |x_{2}|^{2} + |x_{3}|^{2}}$ = $\sqrt{|1|^{2} + |-2|^{2} + |3|^{2}}$ = $\sqrt{14}$ = 3.74165**<br><br>

3. L<sup>$\infty$</sup> Norm: It is called as max norm <br>
For x, given above<br>
**L<sup>$\infty$</sup> of x = max{|x<sub>i</sub>|: i = 1,2,3....} = max{|1|,|-2|,|3|} = 3**

Norm of a vector can be calculated using the method numpy.linalg.norm(). The function takes at least two arguments, i.e., the vector (numpy array) and the order of the norm. The default value for order of norm is 2. So when no 'order' argument is specified, the function calculates the second order norm by default.

For e.g., numpy.linalg.norm(a, 2)

### Angle Between Vectors

<img src="../images/dbv.png", style="width:70%;">

The L<sup>2</sup> Norm can also be written as <br>
**(a<sup>T</sup>)(b) = ||a||<sub>2</sub> ||b||<sub>2</sub> cos($\theta$)** <br>
where $\theta$ is the angle between the two vectors a and b. <br>

Calculating the angle between two vectors is not a straight forward process in Python The following steps can be followed in order to find out the angle between any two vectors.

1. Normalize the given vectors: Normalizing is the process of converting the length of a vector to '1' while preserving the direction of the vector. This can be done by dividing the vector with its second order norm.
2. Dot product of Normalized vectors: Find out the dot product of the normalized vectors from above step using the numpy.dot function.
3. Clipping the value of the dot product: As we are trying to calculate the angle between vectors using the law of cosines, we should note that the cosine function has a maximum value of '1' and minimum value of '-1'. The dot product calculated in previous step cannot have a value beyond these bounds. Hence we use the 'numpy.clip()' function to limit the result of the dot product. If the value of the dot product of the normalized vectors falls within -1 and 1, it retains its value. If it is less than -1 it assumes a value of -1 and if greater than 1, then it assumes a value of 1.
4. Calculating angle using **cos<sup>-1</sup>** function: We have a value between -1 and 1 which we need to use to calculate the possible angle using the inverse cosine function. This can be acheived using the 'numpy.arccos()' function. Note that the arccos() function returns the angle in radians. In order to convert this result into degrees, the 'numpy.degrees()' function can be used.

### Special Vectors and Matrices


If a and b are non-zero vectors and **(a<sup>T</sup>)(b) = 0**, then it implies that **cos($\theta$) = 0**. So, the angle between a and b would be 90 degrees and in such a condition a and b are called orthogonal vectors (with respect to each other).

* Symmetric Matrix: If **a = a<sup>T</sup>** then 'a' is a symmetric matrix
* Orthogonal Matrix: If **a<sup>-1</sup> = a<sup>T</sup>** then 'a' is called an orthogonal matrix.

### Exercise

* Find out the second degree norms of given vectors 'v_one' and 'v_two'. Assign the norms to two variables 'v_one_norm' and 'v_two_norm' and print them out.
* Normalize 'v_one' and 'v_two' by dividing them with their respective norms. Store the values in two variables called 'v_one_normvec' and 'v_two_normvec' and print them out.
* Calculate the angle between 'v_one' and 'v_two'. Use the numpy.degrees function to convert the result of numpy.arccos function from radian into degrees. Assign the angle to a variable 'v_angle' and print it out.
* Are 'v_one' and 'v_two' orthogonal vectors? If yes, store 'True' in the variable 'v_ortho' else store 'False'.

In [23]:
v_one = np.array([1,2,1])
v_two = np.array([3,4,5])

# Modify this code

# v_one_norm = 
# v_two_norm =
# v_one_normvec =
# v_two_normvec =
# v_angle = 
# v_ortho =

### Hint


In [25]:
v_one_norm = np.linalg.norm(v_one,2)
v_two_norm = np.linalg.norm(v_two,2)
print(v_one_norm,v_two_norm)

v_one_normvec = v_one/v_one_norm
v_two_normvec = v_two/v_two_norm
print(v_one_normvec,v_two_normvec)

v_angle = np.degrees(np.arccos(np.clip(np.dot(v_one_normvec,v_two_normvec),-1.0,1.0)))
print(v_angle)

if round(v_angle,2) == 90.00:
    v_ortho = True
else:
    v_ortho = False
    
print(v_ortho)

2.44948974278 7.07106781187
[ 0.40824829  0.81649658  0.40824829] [ 0.42426407  0.56568542  0.70710678]
22.5178253582
False


In [26]:
ref_tmp_var = False

try:
    test1 = round(2.44948974278,2)
    test2 = round(7.07106781187,2)
    test3 = [round(x,2) for x in [0.40824829,0.81649658,0.40824829]]
    test4 = [round(y,2) for y in [0.42426407,0.56568542,0.70710678]]
    test5 = round(22.5178253582,2)
    test6 = False

    if test1 == round(v_one_norm,2) and test2 == round(v_two_norm,2) and test3 == [round(a,2) for a in v_one_normvec] and test4 == [round(b,2) for b in v_two_normvec] and test5 == round(v_angle,2) and test6 == v_ortho:
        ref_assert_var = True
        ref_tmp_var = True
    else:
        ref_assert_var = False
        print('Please follow the instructions given and use the same variables provided in the instructions. ')

except Exception:
    print('Please follow the instructions given and use the same variables provided in the instructions. ')

assert ref_tmp_var

True
