# Array Shape Manipulation

Sometimes a Data Analyst might be required to run shape manipulation algorithms on the data which needs to be changed in shape, dimensions or property so as to be merged or concatenated with another array. Therefore it is really important to know how to perform these fucntions in Python. 

Array shape manipulation is performed by the following functions - 

## Array Shape Flattening

For flattening, **ravel()** function is used. This function returns a flattened one-dimensional array. A copy is made only if needed. The returned array will have the same type as that of the input array. 

### Exercise

Apply ravel function to flatten the multi-dimensional array into a single dimension. For example you can transform
[[1 2 3]
 [4 5 6]] to [1 2 3 4 5 6] by invoking .ravel on the array.
 
 * Flatten the array below, a and assign it to the variable, b.

In [61]:
import numpy as np 
a = np.array([[1,2,3],[4,5,6]])
print('The original array is:' )
print(a) 

The original array is:
[[1 2 3]
 [4 5 6]]


In [62]:
b = a.ravel()
print(b)

[1 2 3 4 5 6]


In [63]:
ref_tmp_var = False

try:
    import numpy as np

    if np.all(b == [1, 2, 3,4, 5, 6]):
        ref_assert_var = True
        ref_tmp_var = True
    else:
        ref_assert_var = False
        print('Please follow the instructions given and use the same variables provided in the instructions.')
except Exception:
    print('Please follow the instructions given and use the same variables provided in the instructions.')

assert ref_tmp_var

True


## Re-Shaping the Array:

In python we can reshape the array, that is change it from 1 dimension to 2 dimension or may be 3 dimension using the function called **reshape()**. In some cases reshape can also be used for flattening but not everytime.

### Exercise

Apply reshape function to reshape the one-dimensional array into a multi-dimensional array. For example you can transform [0 1 2 3 4 5] to [[0 1]
 [2 3]
 [4 5]] by invoking .reshape on the array.
* Reshape the array below, a and assign it to the variable, b.

In [65]:
a = np.array([0, 1, 2, 3 , 4, 5])
print('Original array: ',a,'\n')

Original array:  [0 1 2 3 4 5] 



In [66]:
b=a.reshape(3,2)
print('Array after using reshape function: \n',b)

Array after using reshape function: 
 [[0 1]
 [2 3]
 [4 5]]


In [1]:
ref_tmp_var = False

try:
    import numpy as np

    if np.all(b == [[(0,1),(2,3),(4,5)]]):
        ref_assert_var = True
        ref_tmp_var = True
    else:
        ref_assert_var = False
        print('Please follow the instructions given and use the same variables provided in the instructions.')
except Exception:
    print('Please follow the instructions given and use the same variables provided in the instructions.')

assert ref_tmp_var

Please follow the instructions given and use the same variables provided in the instructions.


## Resizing

Sometimes it required to shrink or expand the current array, this is called **resizing**. Resizing of an array can be changed with **nparray.resize()**

### Exercise

Apply resize to array having 5 elements and resize it to 8 elements. For example you can resize [0 1 2 3 4] to [0 1 2 3 4 0 0 0] by invoking .resize on the array.
* Resize the array a below and print the result.

In [68]:
a=np.arange(5)
print('Original array: ',a,'\n')

Original array:  [0 1 2 3 4] 



In [69]:
a.resize((8,))
print('Array after using res function: \n',a)

Array after using res function: 
 [0 1 2 3 4 0 0 0]


In [70]:
ref_tmp_var = False

try:
    import numpy as np

    if np.all(a == [0, 1, 2, 3, 4, 0, 0, 0]):
        ref_assert_var = True
        ref_tmp_var = True
    else:
        ref_assert_var = False
        print('Please follow the instructions given and use the same variables provided in the instructions.')
except Exception:
    print('Please follow the instructions given and use the same variables provided in the instructions.')

assert ref_tmp_var

True


### Adding a New Dimension:

Indexing with the np.newaxis object allows us to add an axis to an array. Simply put, the newaxis is used to increase the dimension of the existing array by one more dimension, when used once. Thus,

1D array will become 2D array

2D array will become 3D array

3D array will become 4D array and so on..

Example:

Let's say you want to add the following two arrays:

```python
a1 = np.array([1, 2, 3, 4, 5])
a2 = np.array([5, 4, 3])
print('a1:',a1,'\na2:',a2)

a1: [1 2 3 4 5] 
a2: [5 4 3]
```

If we try to add these two arrays, it will show is a **"valueerror"**, but we can add them by changing the axis.

### Exercise

Apply newaxis function to arrays above, print the new transformed array and then add the 2 arrays.
* Transform and add the two arrays and assign it to new variable, b.

In [ ]:
a1 = np.array([1, 2, 3, 4, 5])
a2 = np.array([5, 4, 3])


In [72]:
a1_new=a1[:, np.newaxis]
print('a1_new:',a1_new,'\n')
b = a1_new + a2
print('Addition of two arrays:',b)

a1_new: [[1]
 [2]
 [3]
 [4]
 [5]] 

Addition of two arrays: [[ 6  5  4]
 [ 7  6  5]
 [ 8  7  6]
 [ 9  8  7]
 [10  9  8]]


In [73]:
ref_tmp_var = False

try:
    import numpy as np

    if np.all(a1_new == [[1],[2],[3],[4],[5]]) and np.all(b == [[ 6,  5,  4],[ 7,  6,  5],[ 8,  7,  6],[ 9,  8,  7],[10,  9,  8]]):
        ref_assert_var = True
        print('Hence we can now add the two arrays, these types of data manipulation techniques come really handy for a Data Analyst while preprocessing the data.')
        ref_tmp_var = True
    else:
        ref_assert_var = False
        print('Please follow the instructions given and use the same variables provided in the instructions.')
except Exception:
    print('Please follow the instructions given and use the same variables provided in the instructions.')

assert ref_tmp_var

True


### Transpose of an Array:

In python, transpose of an array can be achienved by using **transpose()** function. This function permutes the dimension of the given array. It returns a view wherever possible. The function takes the following parameters.

numpy.transpose(arr, axes)

* arr: The array to be transposed
* axes: List of ints, corresponding to the dimensions. By default, the dimensions are reversed

### Exercise

Apply transpose function to arrays below, print the new transformed array and take out its transpose. For example you can transpose [[0 1 2],[3 4 5],[6 7 8]] to [[0 3 6],[1 4 7],[2 5 8]] by invoking .transpose on the array.
* Find the transpose of the array and assign it to a variable,b.

In [74]:
a = np.arange(9).reshape(3,3) 
print('The original array is:' )
print(a)

The original array is:
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [75]:
b=np.transpose(a)
print('\n The transposed array is:')
print(b)


 The transposed array is:
[[0 3 6]
 [1 4 7]
 [2 5 8]]


In [76]:
ref_tmp_var = False

try:
    import numpy as np

    if np.all(b == [[0, 3, 6],[1, 4, 7],[2, 5, 8]]):
        ref_assert_var = True
        ref_tmp_var = True
    else:
        ref_assert_var = False
        print('Please follow the instructions given and use the same variables provided in the instructions.')
except Exception:
    print('Please follow the instructions given and use the same variables provided in the instructions.')

assert ref_tmp_var

True
